name: Build RTNativeExporter

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone UE4SS with Epic-access token and patch submodules
        shell: bash
        env:
          EPIC_GITHUB_TOKEN: ${{ secrets.EPIC_GITHUB_TOKEN }}
        run: |
          git config --global url."https://x-access-token:${EPIC_GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
          git config --global url."https://x-access-token:${EPIC_GITHUB_TOKEN}@github.com/".insteadOf "git@github.com:"
          git config --global url."https://x-access-token:${EPIC_GITHUB_TOKEN}@github.com/".insteadOf "ssh://git@github.com/"

          cd cpp-mods
          git clone https://github.com/UE4SS-RE/RE-UE4SS.git
          cd RE-UE4SS

          sed -i 's#git@github.com:#https://x-access-token:'"${EPIC_GITHUB_TOKEN}"'@github.com/#g' .gitmodules
          sed -i 's#ssh://git@github.com/#https://x-access-token:'"${EPIC_GITHUB_TOKEN}"'@github.com/#g' .gitmodules

          git submodule sync --recursive
          git submodule update --init --recursive

      - name: Configure
        run: |
          cd cpp-mods
          cmake -B build -S . -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build RTNativeExporter
        run: |
          cd cpp-mods
          cmake --build build --target RTNativeExporter --verbose

      - name: Upload DLL
        uses: actions/upload-artifact@v4
        with:
          name: RTNativeExporter
          path: cpp-mods/build/RTNativeExporter.dll
